apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: public.ecr.aws/docker/library/python:3.9
        command: ["sh", "-c"]
        args:
          - |
            pip install flask mysql-connector-python

            cat > app.py <<EOF
            from flask import Flask, jsonify
            import mysql.connector
            import os

            app = Flask(__name__)

            db = mysql.connector.connect(
                host=os.environ.get("DB_HOST"),
                user=os.environ.get("DB_USER"),
                password=os.environ.get("DB_PASSWORD"),
                database=os.environ.get("DB_NAME")
            )

            @app.route("/users")
            def users():
                cursor = db.cursor(dictionary=True)
                cursor.execute("SELECT * FROM users")
                result = cursor.fetchall()
                return jsonify(result)

            app.run(host="0.0.0.0", port=3000)
            EOF

            python app.py

        ports:
        - containerPort: 3000

        env:
        - name: DB_HOST
          value: mysql-service

        - name: DB_USER
          value: user

        - name: DB_NAME
          value: testdb

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD